/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Code.Global;
import Code.Security;
import javax.swing.JOptionPane;

/**
 *
 * @author Reece
 */
public class FirstTime extends javax.swing.JFrame {

    Security code = new Security();

    /**
     * Creates new form FirstTime
     */
    public FirstTime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfo = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("First-Time Setup");
        setAlwaysOnTop(true);
        setResizable(false);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtInfo.setEditable(false);
        txtInfo.setText("Welcome to the First-Time Setup!\n\n**WARNING** - This isn't the usual boring stuff! Please read!\n-You will only see this screen ONCE - unless you have noted the recovery key\n-You cannot bypass security without this screen\n-When setting the admin password, it is encrypted and cannot be read without a decoding key, DO NOT DELETE OR COPY THIS FILE.\n-The admin password will be reset if you are using Recovery Mode.\n\nFinally, you will require a USB Key plugged into the computer as of now, this is your first-factor authentication and will grant access to the standard user interface.\n\nSET THIS UP CORRECTLY, OR YOU WILL BE LOCKED OUT\nYou must be logged into your local, or domain administrator account to use this software.\nOpen compmgmt.msc using the run dialog.\nGo to disk management.\nRight-click the usb device you wish to be your new key.\nClick \"Change drive letter and paths\"\nChange the drive letter to F - THIS MUST BE DONE IF YOUR USB IS NOT ALREADY DRIVE F AND MUST BE REDONE IF THE DRIVE LETTER IS CHANGED\n\nOn the next screen, click the \"Generate\" button to generate a unique key between your USB and this computer.\nDO NOT FORGET TO SET THE ADMIN PASSWORD, if you fail to do so, you will be locked out of the admin panel!\n\nClick OK to continue...");
        txtInfo.setAutoscrolls(false);
        txtInfo.setCaretPosition(0);
        txtInfo.setFocusable(false);
        jScrollPane1.setViewportView(txtInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MasterUI().setVisible(true);
        Global.ftime = true;
        try {
            code.setAdminPass("Password5");
            JOptionPane.showMessageDialog(this, "Password is set to: Password5\nYou can change this yourself on the next screen.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Password wasn't set, you'll have the opportunity to do this manually.", "Default Password not set", JOptionPane.WARNING_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtInfo;
    // End of variables declaration//GEN-END:variables
}
