package Logs;

import GUI.MasterUI;

/**
 *
 * @author reece
 */
public class LogLoaderUI extends javax.swing.JFrame {

    public LogLoaderUI(MasterUI admin) {
        initComponents();
        prepLoad(admin);
    }

    private void load(MasterUI admin, LogLoaderUI UI) {
        Thread go = new Thread() {
            @Override
            public void run() {
                new logUI(admin).setVisible(true);
                UI.dispose();
            }
        };
        go.start();
    }
    
    private void prepLoad(MasterUI admin) {
        load(admin, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loading...");
        setFocusableWindowState(false);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Processing.gif"))); // NOI18N
        jLabel1.setText("Loading the log file, please wait...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
