package Logs;

import GUI.MasterUI;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import Code.Security;

/**
 *
 * @author reece8765
 */
public class logUI extends javax.swing.JFrame {

    /**
     * Creates new form logUI
     */
    File file = new File("C:\\RTC\\data.temp");
    Security sec = new Security();


    public logUI(MasterUI admin) {
        initComponents();
        loadLog();
    }

    private void loadLog() {

        if (!file.exists()) {
            createLog();
        } else {

            try {
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String line = br.readLine();

                if (line == null) {
                    txtLog.setText("Log file appears to be empty!\n");
                } else {
                    txtLog.setText("<--START LOG HERE-->\n\n");
                }

                while (line != null) {
                    txtLog.append(line + "\n");
                    line = br.readLine();
                }
                txtLog.append("\n<--END LOG HERE-->");
            } catch (IOException e) {
                txtLog.setText("The log file could not be loaded.\nThis is an error and you should report this bug.\n"
                        + "LOG_LOAD_ERR - " + e);
            }
        }
    }

    private void createLog() {

        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write("");
        } catch (IOException err) {
            JOptionPane.showMessageDialog(this, "Administrative Rights are required for this application to work!\n"
                    + "If andmin rights are not available, consider allowing full access on the following folder:\n"
                    + "C:\\Security\n"
                    + "Failure to do so will result in errors and application failure.", "User Rights", JOptionPane.WARNING_MESSAGE);
        }
        loadLog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Security Logs");
        setAlwaysOnTop(true);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Access Remote - Security Log"));
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        txtLog.setEditable(false);
        txtLog.setColumns(20);
        txtLog.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 10)); // NOI18N
        txtLog.setLineWrap(true);
        txtLog.setRows(5);
        txtLog.setText("Log file did not load correctly. Make sure there are no renamed or deleted files as this could affect the system performance. Please reload the log window. If you still see this message, restart the application and open the security log again. If you continue to see this message, you may need to reset the system. If this does not fix the issue, delete the folder C:\\Security and relaunch the application.");
        txtLog.setWrapStyleWord(true);
        txtLog.setSelectionColor(new java.awt.Color(255, 255, 0));
        jScrollPane2.setViewportView(txtLog);

        btnClear.setText("Clear Log");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        createLog();
        sec.saveLog("The log was reset by master.");
        loadLog();
    }//GEN-LAST:event_btnClearActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables
}
