package Testing;

import Code.Security;
import GUI.LoginUI;

/**
 *
 * @author reece
 */
public class TestLogUI extends javax.swing.JFrame {

    Security sec = new Security();

    /**
     * Creates new form TestingUI
     */
    public TestLogUI() {
        initComponents();
    }

    public void testLog(int total) {
        final int countTo = total;
        Thread begin = new Thread() {

            @Override
            public void run() {
                final int totalVal = countTo;
                int percentage;
                txtTotal.setText("Total to write: " + totalVal);
                for (int i = 1; i <= countTo; i++) {
                    txtCurrent.setText("Current Log: " + i);
                    sec.saveLog(String.format("This is a test. %d of %d", i, totalVal));
                    //Percentage: initial number divided by total number, times 100
                    percentage = (int) getPercentage(totalVal, i);
                    txtPercentage.setText(percentage + "%");
                    prgResult.setValue(percentage);
                }
                brnTest.setEnabled(true);
                txtInput.setEditable(true);
            }
        };
        begin.start();
    }

    private double getPercentage(int total, int i) {
        return (1.0f * i / total) * 100;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brnTest = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        prgResult = new javax.swing.JProgressBar();
        btnClose = new javax.swing.JButton();
        txtCurrent = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        txtPercentage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        brnTest.setText("Test");
        brnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnTestActionPerformed(evt);
            }
        });

        jLabel1.setText("Log files to write: ");

        btnClose.setText("Exit to Login");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        txtCurrent.setText("Current Log: 0");

        txtTotal.setText("Total to write: 0");

        txtPercentage.setText("0%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prgResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(brnTest))
                            .addComponent(btnClose)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCurrent)
                                .addGap(48, 48, 48)
                                .addComponent(txtPercentage))
                            .addComponent(txtTotal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brnTest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prgResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCurrent)
                    .addComponent(txtPercentage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnTestActionPerformed
        int result = Integer.parseInt(txtInput.getText());
        brnTest.setEnabled(false);
        txtInput.setEditable(false);
        testLog(result);
        System.out.println("Testing Thread");
    }//GEN-LAST:event_brnTestActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        new LoginUI().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnTest;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar prgResult;
    private javax.swing.JLabel txtCurrent;
    private javax.swing.JTextField txtInput;
    private javax.swing.JLabel txtPercentage;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
